### ISSUE TITLE
Get segmentation fault after running "import ngraph_onnx.onnx_importer.importer"

### ISSUE THREAD

**Issue by teyenliu** [NervanaSystems/ngraph-onnx#155]
I have followed the installation guide and try to use ngraph-onnx to convert the Resnet50 model as below. But, I got a segmentation fault after running `import ngraph_onnx.onnx_importer.importer`. 

```python
>>> import onnx
>>> onnx_protobuf = onnx.load('resnet50/model.onnx')
>>> from ngraph_onnx.onnx_importer.importer import import_onnx_model
Segmentation fault (core dumped)
```

**Comment by postrational** [comment]
Hi, this may be related to a known issue with ONNX, reported 
here: https://github.com/onnx/onnx/issues/963, 
here: https://github.com/onnx/onnx/issues/1079 
and here: https://github.com/onnx/onnx/issues/1187

Our best workaround is currently to install ONNX from sources, avoiding the binary package from PyPI.
You can do that like using the `--no-binary=onnx` flag when installing with `pip`:
```bash
pip uninstall onnx
pip install onnx==1.2.2 --no-binary=onnx
```

**Comment by postrational** [comment]
This problem should not occur any more with ONNX version 1.3.
Please reopen issue, if you see the problem again.
