### ISSUE TITLE
Could not find a version that satisfies the requirement ngraph-core (from versions: )

### ISSUE THREAD

**Issue by shailensobhee** [NervanaSystems/ngraph-onnx#295]
How can I solve this issue?

Using Intel Distribution for python:
```
python --version
Python 3.6.5 :: Intel Corporation
```

```
pip install ngraph-core ngraph-onnx
Collecting ngraph-core
Could not find a version that satisfies the requirement ngraph-core (from versions: )
No matching distribution found for ngraph-core
```

```
cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Comment by postrational** [comment]
Please use Python 3.5 for now. We are working on adding support for more configurations.
https://pypi.org/project/ngraph-core/#files

**Comment by postrational** [comment]
We now support Python 3.6 and others in PyPI packages:
https://pypi.org/project/ngraph-core/0.18.0/#files

**Comment by abenito32** [comment]
Hi,

I have problems to install Ngraph in raspberry, could you help me? I need to use Ngraph in my python script.

"import ngraph as ng"


pi@raspberrypi:/opt/intel/openvino/deployment_tools/ngraph $ pip3 install ngraph-core --user
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement ngraph-core
ERROR: No matching distribution found for ngraph-core

pi@raspberrypi:/opt/intel/openvino/deployment_tools/ngraph $ cat /etc/os-releasePRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

Thank you,
