### ISSUE TITLE
ONNX importer runtime error: unsupported data type: BOOL

### ISSUE THREAD

**Issue by irnovikov** [NervanaSystems/ngraph-onnx#369]
From this code:
    onnx_protobuf = onnx.load(model_path)
    ng_function = import_onnx_model(onnx_protobuf)

bridge fails like that:
   File "./test_onnx_model.py", line 22, in evaluate
    ng_function = import_onnx_model(onnx_protobuf)
  File "/media/dmitry/BigDisk/rnovikov/ngraph-onnx/venv_onnx_check/lib/python3.6/site-packages/ngraph_onnx/onnx_importer/importer.py", line 36, in import_onnx_model
    return onnx_import.import_onnx_model(onnx_protobuf.SerializeToString())
RuntimeError: unsupported data type: BOOL

source onnx:
https://www.dropbox.com/s/84xnff3bec035dz/wavenet_body.zip?dl=0

**Comment by postrational** [comment]
Unfortunately, at this stage nGraph does not support the `BOOL` data type.

**Comment by postrational** [comment]
`BOOL` type is now supported.
